# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Design/admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Admin_Ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.download = QtWidgets.QPushButton(self.centralwidget)
        self.download.setGeometry(QtCore.QRect(100, 880, 840, 59))
        self.download.setStyleSheet("position: absolute;\n"
"width: 840px;\n"
"height: 59px;\n"
"\n"
"background: #FFFFFF;\n"
"border-radius: 10px;\n"
"font-family: Red Hat Text;\n"
"font-style: normal;\n"
"font-weight: bold;\n"
"font-size: 24px;\n"
"line-height: 0%;")
        self.download.setObjectName("download")
        self.map = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.map.setGeometry(QtCore.QRect(980, 220, 841, 721))
        self.map.setObjectName("map")
        self.database = QtWidgets.QTableWidget(self.centralwidget)
        self.database.setGeometry(QtCore.QRect(100, 220, 841, 641))
        self.database.setStyleSheet("width: 840px;\n"
"height: 641px;\n"
"\n"
"background: #FFFFFF;\n"
"border-radius: 10px;")
        self.database.setObjectName("database")
        self.database.setColumnCount(0)
        self.database.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.download.setText(_translate("MainWindow", "Скачать в csv формате"))
from PyQt5 import QtWebEngineWidgets
