# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Design/edit_message.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class EditMessageUi(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.edit = QtWidgets.QPushButton(self.centralwidget)
        self.edit.setGeometry(QtCore.QRect(1310, 800, 241, 71))
        self.edit.setStyleSheet("position: absolute;\n"
"width: 540px;\n"
"height: 71px;\n"
"\n"
"background: #FFFFFF;\n"
"border-radius: 10px;\n"
"font-family: Red Hat Text;\n"
"font-style: normal;\n"
"font-weight: bold;\n"
"font-size: 24px;\n"
"line-height: 0%;")
        self.edit.setObjectName("edit")
        self.database = QtWidgets.QTableWidget(self.centralwidget)
        self.database.setGeometry(QtCore.QRect(370, 210, 1180, 554))
        self.database.setStyleSheet("position: absolute;\n"
"width: 1180px;\n"
"height: 554px;\n"
"\n"
"background: #FFFFFF;\n"
"border-radius: 10px;")
        self.database.setObjectName("database")
        self.database.setColumnCount(0)
        self.database.setRowCount(0)
        self.id = QtWidgets.QComboBox(self.centralwidget)
        self.id.setGeometry(QtCore.QRect(370, 800, 471, 71))
        self.id.setStyleSheet("position: absolute;\n"
"width: 540px;\n"
"height: 71px;\n"
"\n"
"background: #FFFFFF;\n"
"border-radius: 10px;\n"
"font-family: Red Hat Text;\n"
"font-style: normal;\n"
"font-weight: bold;\n"
"font-size: 24px;\n"
"line-height: 0%;")
        self.id.setObjectName("id")
        self.help = QtWidgets.QPushButton(self.centralwidget)
        self.help.setGeometry(QtCore.QRect(30, 890, 161, 51))
        self.help.setStyleSheet("background: #FFFFFF;\n"
"border-radius: 10px;\n"
"font-family: Red Hat Text;\n"
"font-style: normal;\n"
"font-weight: bold;\n"
"font-size: 24px;\n"
"line-height: 0%;")
        self.help.setObjectName("help")
        self.delete = QtWidgets.QPushButton(self.centralwidget)
        self.delete.setGeometry(QtCore.QRect(1030, 800, 241, 71))
        self.delete.setStyleSheet("position: absolute;\n"
"width: 540px;\n"
"height: 71px;\n"
"\n"
"background: #FFFFFF;\n"
"border-radius: 10px;\n"
"font-family: Red Hat Text;\n"
"font-style: normal;\n"
"font-weight: bold;\n"
"font-size: 24px;\n"
"line-height: 0%;")
        self.delete.setObjectName("delete")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.edit.setText(_translate("MainWindow", "Редактировать"))
        self.help.setText(_translate("MainWindow", "Помощь"))
        self.delete.setText(_translate("MainWindow", "Удалить"))
