# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Design/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class LoginWindowUi(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(False)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-image:url(Background_1.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(760, 170, 402, 293))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.log_in = QtWidgets.QLabel(self.layoutWidget)
        self.log_in.setStyleSheet("font-family: Red Hat Text;\n"
"font-style: normal;\n"
"font-weight: bold;\n"
"font-size: 48px;\n"
"line-height: 154.8%;\n"
"opacity: 0;")
        self.log_in.setAlignment(QtCore.Qt.AlignCenter)
        self.log_in.setObjectName("log_in")
        self.verticalLayout.addWidget(self.log_in)
        self.Login_le = QtWidgets.QLineEdit(self.layoutWidget)
        self.Login_le.setAutoFillBackground(False)
        self.Login_le.setStyleSheet("font-family: Red Hat Text;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 24px;\n"
"line-height: 0%;\n"
"/* or 0px */\n"
"letter-spacing: -0.05em;\n"
"\n"
"color: #000000;\n"
"position: absolute;\n"
"width: 344px;\n"
"height: 51px;\n"
"left: 548px;\n"
"top: 299px;\n"
"\n"
"\n"
"background: #FFFFFF;\n"
"border-radius: 10px;")
        self.Login_le.setInputMask("")
        self.Login_le.setText("")
        self.Login_le.setObjectName("Login_le")
        self.verticalLayout.addWidget(self.Login_le)
        self.Password_le = QtWidgets.QLineEdit(self.layoutWidget)
        self.Password_le.setStyleSheet("position: absolute;\n"
"width: 150px;\n"
"height: 25px;\n"
"left: 570px;\n"
"top: 392px;\n"
"\n"
"font-family: Red Hat Text;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 24px;\n"
"line-height: 0%;\n"
"/* or 0px */\n"
"\n"
"letter-spacing: -0.05em;\n"
"\n"
"color: #000000;\n"
"position: absolute;\n"
"width: 344px;\n"
"height: 51px;\n"
"left: 548px;\n"
"top: 299px;\n"
"\n"
"background: #FFFFFF;\n"
"border-radius: 10px;")
        self.Password_le.setText("")
        self.Password_le.setObjectName("Password_le")
        self.verticalLayout.addWidget(self.Password_le)
        self.sign_in = QtWidgets.QPushButton(self.layoutWidget)
        self.sign_in.setStyleSheet("font-family: Red Hat Text;\n"
"font-style: normal;\n"
"font-weight: bold;\n"
"font-size: 24px;\n"
"line-height: 0%;\n"
"\n"
"position: absolute;\n"
"width: 400px;\n"
"height: 40px;\n"
"left: 520px;\n"
"top: 511px;\n"
"\n"
"background: #CFEBF9;\n"
"border-radius: 10px;")
        self.sign_in.setObjectName("sign_in")
        self.verticalLayout.addWidget(self.sign_in)
        self.sign_up = QtWidgets.QPushButton(self.layoutWidget)
        self.sign_up.setStyleSheet("font-family: Red Hat Text;\n"
"font-style: normal;\n"
"font-weight: bold;\n"
"font-size: 24px;\n"
"line-height: 0%;\n"
"\n"
"position: absolute;\n"
"width: 400px;\n"
"height: 40px;\n"
"left: 520px;\n"
"top: 464px;\n"
"\n"
"background: #CFEBF9;\n"
"border-radius: 10px;")
        self.sign_up.setObjectName("sign_up")
        self.verticalLayout.addWidget(self.sign_up)
        self.Message = QtWidgets.QLabel(self.centralwidget)
        self.Message.setGeometry(QtCore.QRect(730, 460, 461, 31))
        self.Message.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Message.setStyleSheet("font-family: Red Hat Text;\n"
"font-style: normal;\n"
"font-weight: bold;\n"
"font-size: 24px;")
        self.Message.setText("")
        self.Message.setAlignment(QtCore.Qt.AlignCenter)
        self.Message.setObjectName("Message")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Вход"))
        self.log_in.setText(_translate("MainWindow", "Вход"))
        self.Login_le.setPlaceholderText(_translate("MainWindow", "Логин"))
        self.Password_le.setPlaceholderText(_translate("MainWindow", "Пароль"))
        self.sign_in.setText(_translate("MainWindow", "Войти"))
        self.sign_up.setText(_translate("MainWindow", "Зарегестрироваться"))
