# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Design/main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MainMenuWindowUi(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1078)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.edit_message = QtWidgets.QPushButton(self.centralwidget)
        self.edit_message.setGeometry(QtCore.QRect(760, 180, 401, 301))
        self.edit_message.setStyleSheet("width: 390px;\n"
"height: 330px;\n"
"\n"
"background: #3C9897;\n"
"border-radius: 10px;\n"
"font-family: Red Hat Text;\n"
"font-style: normal;\n"
"font-weight: bold;\n"
"font-size: 36px;\n"
"line-height: 48px;\n"
"\n"
"color: #FDFDFD;")
        self.edit_message.setObjectName("edit_message")
        self.message = QtWidgets.QPushButton(self.centralwidget)
        self.message.setGeometry(QtCore.QRect(270, 180, 401, 301))
        self.message.setStyleSheet("width: 390px;\n"
"height: 330px;\n"
"\n"
"background: #3C9897;\n"
"border-radius: 10px;\n"
"font-family: Red Hat Text;\n"
"font-style: normal;\n"
"font-weight: bold;\n"
"font-size: 36px;\n"
"line-height: 48px;\n"
"\n"
"color: #FDFDFD;")
        self.message.setObjectName("message")
        self.status_message = QtWidgets.QPushButton(self.centralwidget)
        self.status_message.setGeometry(QtCore.QRect(1250, 180, 401, 301))
        self.status_message.setStyleSheet("width: 390px;\n"
"height: 330px;\n"
"\n"
"background: #3C9897;\n"
"border-radius: 10px;\n"
"font-family: Red Hat Text;\n"
"font-style: normal;\n"
"font-weight: bold;\n"
"font-size: 36px;\n"
"line-height: 48px;\n"
"\n"
"color: #FDFDFD;")
        self.status_message.setObjectName("status_message")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.edit_message.setText(_translate("MainWindow", "Редактировать \n"
"своё сообщение"))
        self.message.setText(_translate("MainWindow", "Сообщить \n"
"о экологической\n"
" проблеме\n"
" своего города"))
        self.status_message.setText(_translate("MainWindow", "Статус моих \n"
"сообщений"))
