# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Design/message.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MessageWindowUi(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.category = QtWidgets.QLineEdit(self.centralwidget)
        self.category.setGeometry(QtCore.QRect(190, 130, 581, 51))
        self.category.setStyleSheet("position: absolute;\n"
"width: 550px;\n"
"height: 60px;\n"
"\n"
"background: #FFFFFF;\n"
"border-radius: 20px;\n"
"font-family: Red Hat Text;\n"
"font-style: normal;\n"
"font-weight: bold;\n"
"font-size: 20px;\n"
"line-height: 0%;")
        self.category.setObjectName("category")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(770, 10, 371, 71))
        self.label.setStyleSheet("position: absolute;\n"
"width: 400px;\n"
"height: 70px;\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: bold;\n"
"font-size: 65px;\n"
"line-height: 79px;\n"
"\n"
"color: #3C9897;")
        self.label.setObjectName("label")
        self.photo = QtWidgets.QPushButton(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(190, 680, 581, 51))
        self.photo.setStyleSheet("position: absolute;\n"
"width: 550px;\n"
"height: 60px;\n"
"\n"
"background: #FFFFFF;\n"
"border-radius: 20px;\n"
"font-family: Red Hat Text;\n"
"font-style: normal;\n"
"font-weight: bold;\n"
"font-size: 24px;\n"
"line-height: 0%;")
        self.photo.setObjectName("photo")
        self.send = QtWidgets.QPushButton(self.centralwidget)
        self.send.setGeometry(QtCore.QRect(190, 750, 581, 51))
        self.send.setStyleSheet("position: absolute;\n"
"width: 550px;\n"
"height: 60px;\n"
"\n"
"background: #FFFFFF;\n"
"border-radius: 20px;\n"
"font-family: Red Hat Text;\n"
"font-style: normal;\n"
"font-weight: bold;\n"
"font-size: 24px;\n"
"line-height: 0%;")
        self.send.setObjectName("send")
        self.message = QtWidgets.QTextEdit(self.centralwidget)
        self.message.setGeometry(QtCore.QRect(190, 200, 581, 391))
        self.message.setStyleSheet("position: absolute;\n"
"width: 550px;\n"
"height: 390px;\n"
"\n"
"background: #FFFFFF;\n"
"border-radius: 20px;\n"
"font-family: Red Hat Text;\n"
"font-style: normal;\n"
"font-weight: bold;\n"
"font-size: 20px;\n"
"line-height: 0%;")
        self.message.setObjectName("message")
        self.map = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.map.setGeometry(QtCore.QRect(1140, 130, 591, 671))
        self.map.setStyleSheet("position: absolute;\n"
"width: 600px;\n"
"height: 730px;\n"
"\n"
"background: #FFFFFF;\n"
"border-radius: 20px;")
        self.map.setObjectName("map")
        self.apply_address = QtWidgets.QPushButton(self.centralwidget)
        self.apply_address.setGeometry(QtCore.QRect(190, 610, 581, 51))
        self.apply_address.setStyleSheet("position: absolute;\n"
"width: 550px;\n"
"height: 60px;\n"
"\n"
"background: #FFFFFF;\n"
"border-radius: 20px;\n"
"font-family: Red Hat Text;\n"
"font-style: normal;\n"
"font-weight: bold;\n"
"font-size: 24px;\n"
"line-height: 0%;")
        self.apply_address.setObjectName("apply_address")
        self.help = QtWidgets.QPushButton(self.centralwidget)
        self.help.setGeometry(QtCore.QRect(20, 910, 161, 51))
        self.help.setStyleSheet("background: #FFFFFF;\n"
"border-radius: 10px;\n"
"font-family: Red Hat Text;\n"
"font-style: normal;\n"
"font-weight: bold;\n"
"font-size: 24px;\n"
"line-height: 0%;")
        self.help.setObjectName("help")
        self.message.raise_()
        self.category.raise_()
        self.label.raise_()
        self.photo.raise_()
        self.send.raise_()
        self.map.raise_()
        self.apply_address.raise_()
        self.help.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.category.setPlaceholderText(_translate("MainWindow", "Название"))
        self.label.setText(_translate("MainWindow", "ЭКОГОРОД"))
        self.photo.setText(_translate("MainWindow", "ПРИКРЕПИТЬ ФОТО"))
        self.send.setText(_translate("MainWindow", "ОТПРАВИТЬ"))
        self.message.setPlaceholderText(_translate("MainWindow", "Описание"))
        self.apply_address.setText(_translate("MainWindow", "ПОДТВЕРДИТЬ АДРЕС"))
        self.help.setText(_translate("MainWindow", "Помощь"))
from PyQt5 import QtWebEngineWidgets
